[package]
name = "face_https"
version = "0.1.0"
authors = ["Zhong Wei <zhongwei99@163.com>"]
edition = "2018"

[dependencies]
rust-embed="4.3.0"
mime_guess = "2.0.0-alpha.6"
open = "1.2"
env_logger = "0.6.0"
rustls = "0.14.0"
actix = "0.7.9"
actix-web = { version = "0.7.18", features=["rust-tls"] }